Fix shellcheck errors/warnings

diff --git a/bootstrap/create-snapshot b/bootstrap/create-snapshot
--- a/bootstrap/create-snapshot
+++ b/bootstrap/create-snapshot
@@ -4,16 +4,14 @@
 
 [ ! -d ~/.rnode ] && echo "Cannot snapshot: $HOME/.rnode does not exist" && exit 2
 
-cd `dirname $0`
+! cd "$(dirname "$0")" && echo "Could not cd to script directory" && exit 1
 
-./stop-rnode
-if [ $? -ne 0 ] ; then exit $?; fi
+! ./stop-rnode && exit $?
 
 mkdir -p snapshot
 
-TARGET=$PWD/snapshot/$1.tgz
-echo $TARGET TARGET
-[ -f "$TARGET" ] && while read -p "$TARGET already exists. Replace [y]? " response;do
+TARGET="$PWD/snapshot/$1.tgz"
+[ -f "$TARGET" ] && while read -r -p "$TARGET already exists. Replace [y]? " response;do
    if [ "$response" == 'y' ] || [ -z "$response" ]; then
       break
    else
@@ -22,5 +20,5 @@ echo $TARGET TARGET
    fi
 done
 
-(cd ~; tar czf "$TARGET" .rnode)
+(cd ~ && tar czf "$TARGET" .rnode)
 echo "snapshot created: $TARGET"
