Merge branch 'master' into separate-NETWORKS

diff --git a/bootstrap/deploy b/bootstrap/deploy
--- a/bootstrap/deploy
+++ b/bootstrap/deploy
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+./check-rnode
+if [ $? -ne 0 ] ; then exit $?; fi
+
+errorfile=""
+if [ "$1" = "--error" ]; then
+   errorfile=$2;
+   shift 2;
+   echo "Logs Errors to $errorfile";
+fi
+
 private_key=`cat pk.bootstrap`
 lastblock=$(curl -s 'http://localhost:40403/api/blocks/1'|jq '.[].blockNumber')
 for t in $@;do
@@ -9,7 +19,15 @@ for t in $@;do
    --phlo-price 1 \
    --phlo-limit 100000000 \
    --private-key $private_key \
-   $t;then
-      exit 1
+   $t
+   status=$?
+
+   if [ $status -ne 0 ] ; then
+      echo "$0 status $status"
+      if [[ -n "$errorfile" ]]; then
+         echo "./deploy error $status for $t" >>$errorfile
+      fi
+      break;
    fi
 done 2>&1
+exit $status
